# permissions for end users to edit repoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repo-editor-role
rules:
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - repoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - repoes/status
  verbs:
  - get
