---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - schedules/finalizers
  verbs:
  - update
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - schedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
