# permissions for end users to edit schedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schedule-editor-role
rules:
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.k8s.akuz.de
  resources:
  - schedules/status
  verbs:
  - get
